language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

# Tavis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r goonmeonity-springboot-service *
  - mkdir -p deploy
  - mv goonmeonity-springboot-service.zip deploy/goonmeonity-springboot-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: goonmeonity-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: develop

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: goonmeonity-springboot-build
    key: goonmeonity-springboot-service.zip
    bundle_type: zip
    application: goonmeonity-backend-service
    deployment_group: goonmeonity-backend-service-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: develop

notifications:
  email:
    recipients:
      - 'cms3136@gmail.com'