language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

# Tavis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chomod +x gradlew

notifications:
  email:
    recipients:
      - 'cms3136@gmail.com'