version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/goonmeonity_test3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: health.sh
      timeout: 60
      runas: root