version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/goonmeonity_test2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu